language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on
before_install:
  - go get -t -v ./...
script:
  - ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
