on: push
name: workflow-ci
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: run
        uses: cedrickring/golang-action@1.3.0
        env:
          GO111MODULE: "on"

      - name: coverage
        run: "bash <(curl -s https://codecov.io/bash)"
